#pragma once
#define IDI_ICON1 101
#define IDI_ICON_ATTRIBUTES    102
#define IDI_ICON_TERMINALS     103
#define IDI_ICON_EDIT_WITH      104
#define IDI_ICON_SYSTEM_FOLDERS 105
#define IDI_ICON_PASTE_TO_FILE  106
#define IDI_ICON_COPY_NAME      107
#define IDI_ICON_COPY_PATH      108
#define IDI_ICON_TAKE_OWNERSHIP 109
#define IDI_ICON_SETTINGS       110
